#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://49.232.150.194:3306/rbac
#    username: root
#    password: 5201314zFy@
#    type: com.alibaba.druid.pool.DruidDataSource
#mybatis:
#  mapper-locations: classpath*:com/cqsd/data/mapper/*Mapper.xml
#  type-aliases-package: com.cqsd.data.entry.
server:
  port: 8080

logging:
  level:
    com.cqsd.data.mapper: debug

pagehelper:
  #  合理化参数
  reasonable: true
  #如果每一页显示为0，就查询所有数据
  page-size-zero: true
