spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.232.150.194:3306/rbac
    username: root
    password: 5201314zFy@
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath*:com/cqsd/data/mapper/*Mapper.xml
  type-aliases-package: com.cqsd.data.entry
server:
  port: 8080
